name: CI
on:
  push:
    branches:
      - V1
  pull_request:
    branches:
      - V1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build package
        run: yarn pre-publish

  # update:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: ğŸ— Setup repo
  #       uses: actions/checkout@v3

  #     - name: ğŸ“¦ Setup node & Install dependencies
  #       uses: ./.github/actions/setup

  #     - name: ğŸ— Setup EAS
  #       uses: expo/expo-github-action@v8
  #       with:
  #         eas-version: latest
  #         token: ${{ secrets.EXPO_TOKEN }}

  #     - name: ğŸš€ Create preview
  #       uses: expo/expo-github-action/preview@v8
  #       id: preview
  #       with:
  #         command: eas update --auto
  #         comment: true
  #         working-directory: example/
  #       env:
  #         PROJECT_ID: ${{ secrets.CLOUD_PROJECT_ID }}
